const products = [
  {
    _id: '1',
    name: 'Iphone12 mini',
    image: '/images/iphone-12mini.jpg',
    description:
      'Super Retina XDR display,6.1‑inch (diagonal) all‑screen OLED display, 2532‑by‑1170-pixel resolution at 460 ppi,HDR display, Haptic Touch',
    brand: 'Apple',
    category: 'Mobile Product',
    price: 5499,
    countInStock: 7,
    rating: 4.0,
    numReviews: 5,
  },
  {
    _id: '2',
    name: 'Iphone12',
    image: '/images/iphone-12.jpg',
    description:
      'Super Retina XDR display,6.1‑inch (diagonal) all‑screen OLED display, 2532‑by‑1170-pixel resolution at 460 ppi,HDR display, Haptic Touch',
    brand: 'Apple',
    category: 'Mobile Product',
    price: 6799,
    countInStock: 7,
    rating: 4.0,
    numReviews: 5,
  },
  {
    _id: '3',
    name: 'Iphone12 Pro',
    image: '/images/iphone-12pro.jpg',
    description:
      'Super Retina XDR display,6.1‑inch (diagonal) all‑screen OLED display, 2532‑by‑1170-pixel resolution at 460 ppi,HDR display, Haptic Touch',
    category: 'Mobile Product',
    price: 8499,
    countInStock: 10,
    rating: 4.5,
    numReviews: 8,
  },
  {
    _id: '4',
    name: 'Iphone12 Pro Max',
    image: '/images/iphone-12-pro-max.jpg',
    description:
      'Super Retina XDR display,6.7‑inch (diagonal) all‑screen OLED display, 2532‑by‑1170-pixel resolution at 460 ppi,HDR display, Haptic Touch',
    brand: '苹果',
    category: 'Mobile Product',
    price: 9299,
    countInStock: 7,
    rating: 4.0,
    numReviews: 5,
  },
  {
    _id: '5',
    name: 'HuaWei Mate 40 Pro',
    image: '/images/huawei-mate-40-pro.jpg',
    description:
      'Hua Wei Mate 40 Pro is a mobile phone owned by Huawei, equipped with a Kirin processor, a 6.76-inch OLED screen, and a memory configuration of 8GB/12GB. The Huawei Mate40 series has shown more playability in video functions. Super outsole main camera + innovative dual movie lens blessing, with super anti-shake performance, straight out 4K high-quality video.',
    brand: 'Hua Wei',
    category: 'Mobile Product',
    price: 9500,
    countInStock: 5,
    rating: 4.6,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Hua Wei P40 Pro',
    image: '/images/huawei-p40-pro.jpg',
    description:
      'Hua Wei Mate 40 Pro is a mobile phone owned by Huawei, equipped with a Kirin processor, a 6.76-inch OLED screen, and a memory configuration of 8GB/12GB. The Huawei Mate40 series has shown more playability in video functions. Super outsole main camera + innovative dual movie lens blessing, with super anti-shake performance, straight out 4K high-quality video.',
    brand: 'Hua Wei',
    category: 'Mobile Product',
    price: 5988,
    countInStock: 11,
    rating: 4,
    numReviews: 7,
  },
  {
    _id: '7',
    name: 'OnePlus 8T',
    image: '/images/one-plus-8t.jpg',
    description:
      'OnePlus 8T is a smartphone under OnePlus Technology. It is equipped with a Qualcomm Snapdragon 865 processor, uses LPDDR4X memory and UFS3.1 flash memory, and supports a storage combination of up to 12GB+256GB',
    brand: 'Samgsung',
    category: 'Mobile Product',
    price: 3399,
    countInStock: 7,
    rating: 3.8,
    numReviews: 10,
  },
  {
    _id: '8',
    name: 'Xiao Mi 10',
    image: '/images/xiaomi-10.jpg',
    description:
      'X10 Extreme Commemorative Edition supports 120Hz refresh rate, 10bit color depth display and HDR10+ image display. The rear 48-megapixel four-camera supports 8K24 frame video recording, and the rear camera supports up to 120x zoom.',
    brand: 'Xiao Mi ',
    category: 'Mobile Product',
    price: 5299,
    countInStock: 0,
    rating: 4.3,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'vivo NEX 3S',
    image: '/images/vivo-nex-3s.jpg',
    description:
      'vivo NEX 3s is a smartphone developed by vivo, which continues the design style of vivo NEX3. It adopts a 6.89-inch unbounded waterfall screen, a lifting camera, side pressure-sensitive buttons, a Snapdragon 865 processor, a new succinol color scheme, and UFS 3.1 , LPDDR5 memory solution, plug-in Qualcomm X55 5G baseband.',
    brand: 'vivo',
    category: 'Mobile Product',
    price: 4998,
    countInStock: 7,
    rating: 3.8,
    numReviews: 9,
  },
  {
    _id: '10',
    name: 'OPPO Find X2 ',
    image: '/images/oppo-find-x2.jpg',
    description:
      'OPPO Find X2 adopts a 6.7-inch 120Hz ultra-sensitive hole-digging curved screen, with a length of about 164.9 mm and a width of about 74.5 mm. The thickness of the ceramic version is about 8.0 mm, the thickness of the glass version is about 8.0 mm, the thickness of the plain leather version is about 8.7 mm, and the weight of the ceramic version is about 209 grams. The glass version weighs about 192 grams, and the plain leather version weighs about 189 grams.',
    brand: 'oppo',
    category: 'Mobile Product',
    price: 5499,
    countInStock: 15,
    rating: 3.6,
    numReviews: 5,
  },
]

export default products